### ISSUE TITLE
Make the evaluator more robust, speed-up and handle datasets up to 100K docs

### ISSUE THREAD

**Issue by CatStark** [jina-ai/finetuner#512]

**Comment by guenthermi** [comment]
There are several potential improvements of the evaluator:

- [ ] Reduce the memory consumption for large datasets: If the `index_data` contains more than 1M documents, storing all embeddings in memory can become unfeasible. To solve this problem, we can calculate the embeddings of the `index_data` and perform the matching only batch-wise. Later on we can merge the matches with the matches of the subsequent batches to obtain the global top-k results
- [ ] Restrict the number of queries in cases where the user only provides one document array dataset: If the evaluator is only initilaized with a `query_da`. The same DocumentArray is uses as query and index set. In this way, each document is compared to each other document in the dataset. This leads to an quadratic growth in the number of similarity calculations. In order to prevent this, we could either sample a smaller query set for large datasets (this should not have much influence on the metrics, since most of them are averaged over all queries) or force the user provide always an `index_da` dataset.
- [ ] Allow user to specify two separate models for encoding `query_da` and `index_da`: Currently, the evaluator is able to evaluate clip models on text-to-image or image-to-text retrieval task, since it can only use one model for encoding both datasets.

**Comment by guenthermi** [comment]
I evaluated to improvements to prevent high memory consumption:
- By calculating the embeddings of the index_data in batches and also perform the matching independently on the batches, we do not need to store the embeddings of all documents in the index at once in the main memory:
Reduction: 1.709GB -> 0.651GB (for index data with 100K 1000-dim embeddings in batches of 10k documents)
- In the case where many queries share the same label, the current implementation constructs an equal `DocumentArray` (the ground truth to compare with) with the matching ids for each of those queries . To make this more efficient, all queries can share the same `DocumentArray`
Reduction: 0.948GB -> 0.296GB (for 1000 queries with 1000 matches with the same label)

**Comment by guenthermi** [comment]
Regarding the speed, the batch-wise evaluation is slightly slower. However, the difference gets smaller if the batch size (or the number of queries) gets higher. 

For 100 queries, 100k documents with 1000-dim vectors, and a simple linear model:
batch-wise (10k): 18s vs single batch 16s

On a real dataset (5000k queries and 15k documents from the quora dataset), sbert model, the embedding calculation tasks much more time and the difference is not noticable:
batch-wise 321.31s vs single batch 321.51s

**Comment by CatStark** [comment]
Reference: https://www.notion.so/Draft-for-Evaluate-Refactoring-f1755462adab492b864da3b7b3287133

**Comment by CatStark** [comment]
Will be done after the #557

**Comment by guenthermi** [comment]
Parts of the issues are done in docarray. The tickets are tracked here: https://github.com/jina-ai/docarray/issues/568

**Comment by CatStark** [comment]
https://github.com/docarray/docarray/pull/731

**Comment by guenthermi** [comment]
https://github.com/docarray/docarray/pull/826
